using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using UnityEngine;
using IExternalCodeEditor = Unity.CodeEditor.IExternalCodeEditor;
using UCE = Unity.CodeEditor.CodeEditor;
using IOPath = System.IO.Path;

namespace Unity.Devin.Editor
{
	internal static class ReflectedProjectSync
	{
		// Preference order: Rider generates SDK-style projects compatible with .NET Core SDK MSBuild.
		// VS Tools generates old-style projects that require Visual Studio — listed as fallback only.
		private static readonly string[] PreferredEditorNames =
		{
			"Rider",
			"VisualStudioCode",
			"VisualStudio",
		};

		private static IExternalCodeEditor _cachedDelegate;

		public static IExternalCodeEditor FindDelegate()
		{
			if (_cachedDelegate != null)
				return _cachedDelegate;

			var editors = GetRegisteredEditors();

			foreach (var preferred in PreferredEditorNames)
			{
				var found = editors.FirstOrDefault(e =>
					!(e is DevinEditor) &&
					e.GetType().FullName?.IndexOf(preferred, StringComparison.OrdinalIgnoreCase) >= 0);

				if (found != null)
					return _cachedDelegate = found;
			}

			return _cachedDelegate = editors.FirstOrDefault(e => !(e is DevinEditor));
		}

		public static void InvalidateCache() => _cachedDelegate = null;

		public static bool TrySync(IExternalCodeEditor delegateEditor)
		{
			if (delegateEditor == null)
			{
				Debug.LogWarning("[Devin] No compatible editor found for project generation. Install Rider or VS Tools for Unity.");
				return false;
			}

			try
			{
				delegateEditor.SyncAll();
				WriteOmniSharpSupport();
				Debug.Log($"[Devin] Project files synced via {delegateEditor.GetType().Name}.");
				return true;
			}
			catch (Exception ex)
			{
				Debug.LogWarning($"[Devin] SyncAll via {delegateEditor.GetType().Name} failed: {ex.Message}");
				return false;
			}
		}

		public static bool TrySyncIfNeeded(IExternalCodeEditor delegateEditor,
			string[] added, string[] deleted, string[] moved, string[] movedFrom, string[] imported)
		{
			if (delegateEditor == null)
				return false;

			try
			{
				delegateEditor.SyncIfNeeded(added, deleted, moved, movedFrom, imported);
				return true;
			}
			catch (Exception ex)
			{
				Debug.LogWarning($"[Devin] SyncIfNeeded via {delegateEditor.GetType().Name} failed: {ex.Message}");
				return false;
			}
		}

		// After delegate editor generates .csproj/.sln we write OmniSharp-specific support files.
		private static void WriteOmniSharpSupport()
		{
			var projectDirectory = IOPath.GetDirectoryName(Application.dataPath);
			var projectName = IOPath.GetFileName(projectDirectory);

			WriteDirectoryBuildProps(projectDirectory);
			WriteOmniSharpJson(projectDirectory, projectName);
		}

		private static void WriteDirectoryBuildProps(string projectDirectory)
		{
			const string newline = "\r\n";

			var content =
				"<!-- Generated by Unity.Devin — do not edit manually -->" + newline +
				"<Project>" + newline +
				"  <PropertyGroup>" + newline +
				"    <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>" + newline +
				"    <NoRestore>true</NoRestore>" + newline +
				"  </PropertyGroup>" + newline +
				"</Project>" + newline;

			WriteIfChanged(IOPath.Combine(projectDirectory, "Directory.Build.props"), content);
		}

		private static void WriteOmniSharpJson(string projectDirectory, string projectName)
		{
			var solutionPath = IOPath.Combine(projectDirectory, projectName + ".sln").Replace("\\", "\\\\");

			var content =
				"{\r\n" +
				"  \"msbuild\": {\r\n" +
				$"    \"solution\": \"{solutionPath}\",\r\n" +
				"    \"loadProjectsOnDemand\": false,\r\n" +
				"    \"enablePackageAutoRestore\": false,\r\n" +
				"    \"Properties\": {\r\n" +
				"      \"DesignTimeBuild\": \"true\"\r\n" +
				"    }\r\n" +
				"  },\r\n" +
				"  \"RoslynExtensionsOptions\": {\r\n" +
				"    \"EnableAnalyzersSupport\": false,\r\n" +
				"    \"AnalyzeOpenDocumentsOnly\": true,\r\n" +
				"    \"EnableImportCompletion\": true,\r\n" +
				"    \"DiagnosticWorkersThreadCount\": 4,\r\n" +
				"    \"DocumentAnalysisTimeoutMs\": 15000\r\n" +
				"  }\r\n" +
				"}";

			var filePath = IOPath.Combine(projectDirectory, "omnisharp.json");

			if (File.Exists(filePath))
			{
				var existing = File.ReadAllText(filePath);
				if (existing.Contains("\"solution\"") && existing.Contains("loadProjectsOnDemand"))
					return;
			}

			File.WriteAllText(filePath, content, Encoding.UTF8);
		}

		private static void WriteIfChanged(string filePath, string content)
		{
			if (File.Exists(filePath) && File.ReadAllText(filePath, Encoding.UTF8) == content)
				return;

			File.WriteAllText(filePath, content, Encoding.UTF8);
		}

		private static IExternalCodeEditor[] GetRegisteredEditors()
		{
			var codeEditorType = typeof(UCE);

			// Unity stores registered editors in a private static list field.
			// Field name varies by Unity version — iterate all static fields to find it.
			foreach (var field in codeEditorType.GetFields(BindingFlags.NonPublic | BindingFlags.Static))
			{
				if (!typeof(IEnumerable).IsAssignableFrom(field.FieldType))
					continue;

				var value = field.GetValue(null);
				if (value is not IEnumerable enumerable)
					continue;

				var result = new List<IExternalCodeEditor>();
				foreach (var item in enumerable)
				{
					if (item is IExternalCodeEditor editor)
						result.Add(editor);
				}

				if (result.Count > 0)
					return result.ToArray();
			}

			return Array.Empty<IExternalCodeEditor>();
		}
	}
}
